# permissions for end users to view digins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digin-viewer-role
rules:
- apiGroups:
  - research.ibm.dev
  resources:
  - digins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - research.ibm.dev
  resources:
  - digins/status
  verbs:
  - get
